const { chromium } = require('playwright');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const server = http.createServer((req, res) => {
    const name = req.url === '/' ? 'index.html' : req.url.slice(1);
    if (!/^[a-zA-Z0-9.-]+$/.test(name)) { res.writeHead(404).end(); return; }
    const file = path.join(__dirname, name);
    if (!fs.existsSync(file)) { res.writeHead(404).end(); return; }
    res.setHeader('Content-Type', name.endsWith('.js') ? 'application/javascript' : name.endsWith('.css') ? 'text/css' : 'text/html');
    res.end(fs.readFileSync(file));
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  let browser;
  try {
    browser = await chromium.launch({ channel: 'msedge', headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.goto(`http://127.0.0.1:${server.address().port}`);
    const open = () => page.locator('[data-target="family-tree"]').click();
    const save = () => page.getByRole('button', { name: 'Save culture', exact: true }).click();
    await open();
    assert.match(await page.locator('#culture-tree').innerText(), /first source/);
    await page.locator('#culture-name').fill('Oyster master'); await page.locator('#culture-species').fill('Pleurotus ostreatus'); await save();
    await page.locator('#culture-add-child').click(); await page.locator('#culture-name').fill('Oyster clone'); await page.locator('#culture-method').selectOption('Clone'); await save();
    await page.locator('#culture-new').click(); await page.locator('#culture-name').fill('Second source'); await page.locator('#culture-species').fill('Pleurotus ostreatus'); await save();
    await page.locator('#culture-add-child').click(); await page.locator('#culture-name').fill('Oyster cross'); await page.locator('#culture-method').selectOption('Cross');
    await page.locator('#culture-parent-1').selectOption({ label: 'Oyster clone' }); await save();
    assert.equal(await page.locator('#culture-ancestry button').count(), 3);
    assert.equal(await page.locator('.mycelium-link').count(), 3, 'Visual tree lost a cross parent link');
    await page.locator('#culture-notes').fill('Selected for observation'); await save();
    await page.reload(); await open(); await page.getByRole('button', { name: 'Edit Oyster cross', exact: true }).click();
    assert.equal(await page.locator('#culture-notes').inputValue(), 'Selected for observation');
    await page.locator('#culture-search').fill('Oyster clone');
    assert.equal(await page.getByRole('button', { name: 'Edit Second source', exact: true }).count(), 0);
    assert.equal(await page.getByRole('button', { name: 'Edit Oyster master', exact: true }).count(), 1);
    await page.locator('#culture-search').fill('');
    await page.getByRole('button', { name: 'Edit Oyster master', exact: true }).click();
    await page.locator('#culture-method').selectOption('Transfer'); await page.locator('#culture-parent-0').selectOption({ label: 'Oyster clone' }); await save();
    assert.match(await page.locator('#culture-status').innerText(), /circular/);
    await page.getByRole('button', { name: 'Edit Oyster cross', exact: true }).click();
    await page.locator('#culture-collapse').click();
    assert.equal(await page.getByRole('button', { name: 'Edit Oyster clone', exact: true }).isVisible(), false);
    await page.getByRole('button', { name: 'Expand descendants of Oyster master', exact: true }).click();
    assert.equal(await page.getByRole('button', { name: 'Edit Oyster clone', exact: true }).isVisible(), true);
    await page.locator('#culture-expand').click();
    assert.equal(await page.getByRole('button', { name: 'Edit Oyster clone', exact: true }).isVisible(), true);
    await save();
    await page.locator('#culture-fit').click();
    const fitZoom = await page.locator('#culture-zoom-label').innerText(); await page.locator('#culture-zoom-in').click(); assert.notEqual(await page.locator('#culture-zoom-label').innerText(), fitZoom); await page.locator('#culture-fit').click();
    await page.getByRole('button', { name: 'Add child of Oyster cross', exact: true }).click(); assert.equal(await page.locator('#culture-name').inputValue(), ''); assert.equal(await page.locator('#culture-parent-0 option:checked').innerText(), 'Oyster cross');
    await page.getByRole('button', { name: 'Edit Oyster cross', exact: true }).click();
    const downloadPromise = page.waitForEvent('download'); await page.locator('#culture-export').click(); const download = await downloadPromise;
    const exported = JSON.parse(fs.readFileSync(await download.path(), 'utf8')); assert.equal(exported.length, 4);
    fs.mkdirSync(path.join(__dirname, 'qa'), { recursive: true });
    await page.locator('#family-tree').screenshot({ path: path.join(__dirname, 'qa', 'family-tree-desktop.png') });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Page overflows mobile width');
    await page.locator('#family-tree').screenshot({ path: path.join(__dirname, 'qa', 'family-tree-mobile.png') });
    await page.setViewportSize({ width: 1440, height: 1100 });
    await page.locator('[data-target="genetics"]').click();
    assert.match(await page.locator('#genetics-history').innerText(), /No observations yet/);
    await page.locator('#genetics-save').click();
    assert.equal(await page.locator('#genetics-history article').count(), 0);
    await page.locator('#genetics-culture').fill('Oyster master'); await page.locator('#genetics-notes').fill('Even growth observed'); await page.locator('#genetics-passage').fill('2'); await page.locator('#genetics-condition').selectOption('Steady'); await page.locator('#genetics-save').click();
    assert.match(await page.locator('#genetics-history').innerText(), /Even growth observed/);
    await page.reload(); await page.locator('[data-target="genetics"]').click();
    await page.locator('#genetics-history button').click();
    assert.equal(await page.locator('#genetics-passage').inputValue(), '2');
    assert.equal(await page.locator('#genetics-condition').inputValue(), 'Steady');
    await page.locator('#genetics-notes').fill('Updated growth note'); await page.locator('#genetics-save').click();
    assert.equal(await page.locator('#genetics-history article').count(), 1);
    assert.match(await page.locator('#genetics-history').innerText(), /Updated growth note/);
    await page.locator('#genetics-search').fill('no such culture'); assert.equal(await page.locator('#genetics-history article').count(), 0);
    await page.locator('#genetics-search').fill('Oyster'); assert.equal(await page.locator('#genetics-history article').count(), 1);
    await page.locator('#genetics-history button').click(); await page.locator('#genetics-notes').fill('Discard this'); await page.locator('#genetics-cancel').click();
    assert.match(await page.locator('#genetics-history').innerText(), /Updated growth note/);
    const observationsDownload = page.waitForEvent('download'); await page.locator('#genetics-export').click(); const observations = JSON.parse(fs.readFileSync(await (await observationsDownload).path(), 'utf8')); assert.equal(observations[0].passage, 2);
    await page.screenshot({ path: path.join(__dirname, 'qa', 'genetics-desktop.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Genetics overflows mobile width');
    await page.screenshot({ path: path.join(__dirname, 'qa', 'genetics-mobile.png'), fullPage: true });
    assert.deepEqual(errors, []);
    console.log('PASS genetics browser: required inputs, save, reload, edit without duplicates, search, cancel, export and desktop/mobile layout.');
    console.log('PASS browser: source/child/cross, ancestry, edit, reload persistence, search, cycle rejection, collapse/expand, export, desktop/mobile layout; no script errors.');
  } finally { if (browser) await browser.close(); server.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
